import Head from "next/head";
import type { FC, ReactNode } from "react";

interface HeaderProps {
  children?: ReactNode;
}

const Header: FC<HeaderProps> = ({ children }) => {
  const titleAddOn = children ? ` | ${children}` : "";
  const appTitle = `QuizApp${titleAddOn}`;
  return (
    <Head>
      <title>{appTitle}</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link href="/favicon2.ico" rel="icon" />
    </Head>
  );
};

export default Header;
